force-app/main/default/objects/BoardActivity__c.object
<CustomObject>
    <fields>
        <fullName>ActivityType__c</fullName>
        <label>Activity Type</label>
        <referenceTo>BoardActivityType__c</referenceTo>
        <relationshipLabel>Board Activities</relationshipLabel>
        <relationshipName>ActivityTypes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Board Activity</label>
    <nameField>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Board Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BoardActivityType__c.object
<CustomObject>
    <label>Board Activity Type</label>
    <nameField>
        <label>Activity Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Board Activity Types</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/KanbanBoard__c.object
<CustomObject>
    <label>Kanban Board</label>
    <nameField>
        <label>Board Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Kanban Boards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/tests/KanbanBoardServiceTest.cls
@IsTest
private class KanbanBoardServiceTest {
    private static final String ACTIVITY_TYPE_NAME = 'Activity Type #2';

    @TestSetup
    static void setup() {
        BoardActivityType__c boardActivityType = TestFactory.createBoardActivityType(ACTIVITY_TYPE_NAME);
        TestFactory.createBoardActivity();
        TestFactory.createBoardActivity(boardActivityType.Id);
    }

    @IsTest
    static void updateActivityTypeTest() {
        BoardActivity__c boardActivityBefore = [SELECT Id, ActivityType__c FROM BoardActivity__c LIMIT 1];
        BoardActivityType__c boardActivityType = [SELECT Id FROM BoardActivityType__c LIMIT 1];

        Test.startTest();
        new KanbanBoardService().updateActivityType(boardActivityType.Id, boardActivityBefore.Id);
        Test.stopTest();

        BoardActivity__c boardActivityAfter = [SELECT Id, ActivityType__c FROM BoardActivity__c LIMIT 1];
        System.assertNotEquals(boardActivityBefore.ActivityType__c, boardActivityAfter.ActivityType__c);
    }

    @IsTest
    static void getBoardActivitiesTest() {
        KanbanBoard__c kanbanBoard = [SELECT Id, Name FROM KanbanBoard__c WHERE Name = :TestFactory.BOARD_NAME LIMIT 1];

        Test.startTest();
        KanbanBoardService.Board boardActivities = new KanbanBoardService().getBoardActivities(kanbanBoard.Id);
        Test.stopTest();

        System.assertNotEquals(0, boardActivities.sections[0].sectionItems.size());
    }
}