force-app/main/default/objects/BoardActivity__c.object
<CustomObject>
    <fields>
        <fullName>ActivityType__c</fullName>
        <label>Activity Type</label>
        <referenceTo>BoardActivityType__c</referenceTo>
        <relationshipLabel>Board Activities</relationshipLabel>
        <relationshipName>ActivityTypes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Board Activity</label>
    <nameField>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Board Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BoardActivityType__c.object
<CustomObject>
    <fields>
        <fullName>Available_Status__c</fullName>
        <label>Available Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>To Do</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Done</fullName>
                </value>
                <value>
                    <fullName>Code Review</fullName>
                </value>
                <value>
                    <fullName>Ready for QA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Board__c</fullName>
        <label>Board</label>
        <referenceTo>KanbanBoard__c</referenceTo>
        <relationshipLabel>Board Activity Types</relationshipLabel>
        <relationshipName>KanbanBoards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Board Activity Type</label>
    <nameField>
        <label>Activity Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Board Activity Types</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/KanbanBoard__c.object
<CustomObject>
    <label>Kanban Board</label>
    <nameField>
        <label>Board Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Kanban Boards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/KanbanBoardSelector.cls
public with sharing class KanbanBoardSelector {

    public List<KanbanBoard__c>getBoards() {
        return [SELECT Id, Name FROM KanbanBoard__c];
    }

    public BoardActivity__c getBoardActivityById(String activityId) {
        return [SELECT Id, ActivityType__c FROM BoardActivity__c WHERE Id = :activityId LIMIT 1];
    }

    public BoardActivityAttachment__c getBoardActivityAttachmentByFilePath(String filePath) {
        return [
                SELECT
                        BoardActivity__c,
                        DropBoxFileId__c,
                        DropBoxFilePath__c,
                        DropBoxFileURL__c,
                        Name
                FROM BoardActivityAttachment__c
                WHERE DropBoxFilePath__c = :filePath
                LIMIT 1
        ];
    }

    public Map<Id, BoardActivityType__c> getBoardActivityTypes(String boardId) {
        return new Map<Id, BoardActivityType__c>([
                SELECT Available_Status__c,
                        Board__c,
                        Id,
                        Name
                FROM BoardActivityType__c
                WHERE Board__c = :boardId
        ]);
    }

    public Map<Id, BoardActivity__c> getBoardActivitiesByType(Set<Id> activityTypes) {
        return new Map<Id, BoardActivity__c>([
                SELECT ActivityType__c,
                        ActivityType__r.Name,
                        Id,
                        Name,
                        Status__c,
                        Attachments__c
                FROM BoardActivity__c
                WHERE ActivityType__c IN :activityTypes
        ]);
    }

    public List<BoardActivityAttachment__c> getActivityAttachments(String activityId) {
        return [
                SELECT
                        BoardActivity__c,
                        DropBoxFileId__c,
                        DropBoxFilePath__c,
                        DropBoxFileURL__c,
                        Id,
                        Name
                FROM BoardActivityAttachment__c
                WHERE BoardActivity__c = :activityId
        ];
    }

}