force-app/main/default/objects/BoardActivity__c.object
<CustomObject>
    <fields>
        <fullName>ActivityType__c</fullName>
        <label>Activity Type</label>
        <referenceTo>BoardActivityType__c</referenceTo>
        <relationshipLabel>Board Activities</relationshipLabel>
        <relationshipName>ActivityTypes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Board Activity</label>
    <nameField>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Board Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BoardActivityType__c.object
<CustomObject>
    <fields>
        <fullName>Board__c</fullName>
        <label>Board</label>
        <referenceTo>KanbanBoard__c</referenceTo>
        <relationshipLabel>Board Activity Types</relationshipLabel>
        <relationshipName>KanbanBoards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Board Activity Type</label>
    <nameField>
        <label>Activity Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Board Activity Types</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/KanbanBoard__c.object
<CustomObject>
    <label>Kanban Board</label>
    <nameField>
        <label>Board Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Kanban Boards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/TestFactory.cls
@IsTest
public class TestFactory {
    public static String BOARD_NAME = 'Test Board';
    public static String ACTIVITY_TYPE_NAME = 'Test Activity Type';
    public static String ACTIVITY_NAME = 'Test Activity';

    public static KanbanBoard__c createBoard() {
        KanbanBoard__c board = new KanbanBoard__c(Name = BOARD_NAME);
        insert board;
        return board;
    }

    public static BoardActivityType__c createBoardActivityType(String activityTypeName) {
        KanbanBoard__c board = createBoard();
        BoardActivityType__c boardActivityType = new BoardActivityType__c(Name = activityTypeName, Board__c = board.Id);
        insert boardActivityType;
        return boardActivityType;
    }

    public static BoardActivityType__c createBoardActivityType() {
        return createBoardActivityType(ACTIVITY_TYPE_NAME);
    }

    public static BoardActivity__c createBoardActivity(String activityName) {
        BoardActivityType__c boardActivityType = createBoardActivityType();
        BoardActivity__c boardActivity = new BoardActivity__c(
                Name = activityName,
                Status__c = 'Open',
                ActivityType__c = boardActivityType.Id);
        insert boardActivity;
        return boardActivity;
    }

    public static BoardActivity__c createBoardActivity(Id boardActivityTypeId) {
        BoardActivityType__c boardActivityType = createBoardActivityType();
        BoardActivity__c boardActivity = new BoardActivity__c(
                Name = ACTIVITY_NAME,
                Status__c = 'Open',
                ActivityType__c = boardActivityTypeId);
        insert boardActivity;
        return boardActivity;
    }

    public static BoardActivity__c createBoardActivity() {
        return createBoardActivity(ACTIVITY_NAME);
    }
}